import { type } from "@testing-library/user-event/dist/type";

const dataUserFollowing = [
  {
    username: "kiet.lac.792740",
    name: "Tuấnn Kiệtt",
    hide: false,
    verified: false,
    image: "",
    type: "follower",
  },
  {
    username: "cdsmtp",
    name: "Chu Duc Sang",
    hide: false,
    verified: true,
    image: "",
    type: "follower",
  },
  {
    username: "fus.n07",
    name: "Trần Phú",
    hide: false,
    verified: true,
    image: "",
    type: "follower",
  },
  {
    username: "babiv15",
    name: "Han Vu Dinh",
    hide: false,
    verified: true,
    image: "",
    type: "follower",
  },
  {
    username: "im.ph.0621",
    name: "Phong",
    hide: false,
    verified: false,
    image: "",
    type: "follower",
  },
  {
    username: "_cpanz4",
    name: "Phan Hoàng Cương",
    hide: false,
    verified: false,
    image: "",
    type: "follower",
  },
  {
    username: "pimhtnn__",
    name: "",
    hide: false,
    verified: false,
    image: "",
    type: "follower",
  },
  {
    username: "one_three_three_zero",
    name: "My name is Portnoy",
    hide: false,
    verified: false,
    image: "",
    type: "follower",
  },
  {
    username: "m.heiii__",
    name: "Ngọc Mai",
    hide: false,
    verified: false,
    image: "",
    type: "follower",
  },
  {
    username: "ntan.144",
    name: "Ánh Nguyệt",
    hide: false,
    verified: false,
    image: "",
    type: "follower",
  },
  {
    username: "nguyenxtramy",
    name: "Nguyen Tra My",
    hide: false,
    verified: false,
    image: "",
    type: "follower",
  },
  {
    username: "pkvnn.19",
    name: "Khánh Vân",
    hide: false,
    verified: false,
    image: "",
    type: "follower",
  },
  {
    username: "hoaisme.ig",
    name: "Bùi Hữu Hòa",
    hide: false,
    verified: false,
    image: "",
    type: "follower",
  },
  {
    username: "xuanhoa.1212",
    name: "Xuân Hoà",
    hide: false,
    verified: false,
    image: "",
    type: "follower",
  },
];

export default dataUserFollowing;
